### ISSUE TITLE
64x duplication (item to stack)

### ISSUE THREAD

**Issue by 12foo** [CD4017BE/InductiveLogistics#1]
Hiya,

I'm playing around with your mod and liking it so far. However I'm having an issue where I've got a tree farm using Actually Additions long range breakers breaking the trees. I use IL extraction pipes to extract the blocks from the breakers' inventories, and an insertion pipe to insert them into the output chest of the tree farm. Whenever I insert one wood block in one of the breakers, it disappears (so far so good), but a whole stack (so 64 wood) appears in the chest instead!

Edited to add: I'm on Minecraft 1.12.2.

**Comment by CD4017BE** [comment]
Interesting, I had already had a similar bug and fixed it some time ago. It seems that I probably missed something.

**Comment by CD4017BE** [comment]
And please tell if you had filters on any of these pipes and if so, how exactly they were configured.

**Comment by 12foo** [comment]
No filters on the pipes. The setup is basically just

```
B   C   B
E---I---E
```
where B = Breaker, C = Chest, E = Extraction Pipe, I = Insertion Pipc and - just being a regular pipe. Another item collector makes sure only wood goes into the breakers by picking up all other items as they drop, but that collector is hooked up to a different system.

**Comment by CD4017BE** [comment]
Yes, I was able to replicate that bug. But I also found out that it does not happen if you apply a Filter on the pipe extracting from the Breaker. (At least if not configured to accept everything)
Which you could use temporarily until I fixed that bug.

**Comment by 12foo** [comment]
Ah, that's good to know! Thanks.
