### ISSUE TITLE
Cannot render block properly when covering a grass block to pipes

### ISSUE THREAD

**Issue by Snownee** [CD4017BE/InductiveLogistics#12]
![2018-01-18_04 35 50](https://user-images.githubusercontent.com/16059084/35065743-1b126ccc-fc09-11e7-9143-32de87591125.png)
Version 1.1.1
Forge 14.23.1.2583

**Comment by CD4017BE** [comment]
I fixed it ... almost. Do you think people would notice these rendering glitches?
![2018-01-21_22 10 15](https://user-images.githubusercontent.com/14052288/35199024-18400e86-fef8-11e7-914e-7572fee0d00a.png)

**Comment by Snownee** [comment]
Thanks a lot. It's very useful.
