### ISSUE TITLE
Using Sand (and possibly other blocks) as pipe covers causes strange rendering

### ISSUE THREAD

**Issue by brisingraerowing** [CD4017BE/InductiveLogistics#16]
[Image](https://imgur.com/a/meYhq)

The pipe in the middle has a sand cover.

ID: 1.1.3
CD4017BE Lib: 6.2.0

**Comment by CD4017BE** [comment]
use [CD4017BE_lib-6.2.1](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v6.2.1) that should have fixed this.
