### ISSUE TITLE
[1.11.2] Portable Inventory Remote Access

### ISSUE THREAD

**Issue by TheSnowyChickens** [CD4017BE/InductiveLogistics#18]
### What I did:
-Portable Inventory Remote Access is connected to a drawer controller

### What happened:
-if to much drawers are connected and the GUI is set to "Large", then this happend : 
![2018-04-27_17 54 10](https://user-images.githubusercontent.com/29357962/39372216-0d700410-4a44-11e8-81dc-e27f1e4bd185.png)
 
### What should have happened:
-not cut up the inventory and the top of the interface

### Used Versions:
- Minecraft: Ages of Time (Age 2) :)

PS: Es wurde dir ja glaube schonmal von Minion gesagt, das dies eventuell auftreten kann, habs nun erreicht und hier mit "reported". :D

**Comment by Rixxaw** [comment]
Neat! I had no idea this was even a thing... I need to check it out :+1: 

Obvious work around is to change your GUI size?  I assume the Mod Author could add a Scroll bar or something and some sort of option to adjust the GUI size, but I don't believe this was ever intended to be an AE2 wireless terminal.  LUL
