### ISSUE TITLE
Crash with Universal Transport pipes (1.12.2-1.1.3)

### ISSUE THREAD

**Issue by BenB196** [CD4017BE/InductiveLogistics#20]
### What I did:
I placed two universal transport pipes down in my world, they were below two machines and above a chest. (No picture as world is keeps crashing on load.)

### What happened:
After placing the second pipe my server crashed.

Crash Log: https://pastebin.com/rz47Zi5i

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.1.3 (also crashes on 1.2.0)
- CD4017BE_lib-6.2.3 (also crashes on 6.2.1)
- Forge-14.23.2.2651
- Other Mods: The machines are from Integrated Dynamics (1.12.2-0.11.9) and are mechanical squeezers. The chest is from Iron Chests (1.12.2-7.0.40.824) and is a diamond chest
- Config changes: Sevtech mod pack config, changes unknown.

**Comment by BenB196** [comment]
I have removed the two pipes through MCedit, below is a picture that shows where the pipes where, but i put mekanism pipes in place of them.
<img width="1700" alt="crashpic" src="https://user-images.githubusercontent.com/8277432/39536859-d5a06c94-4e05-11e8-9b26-c08a61159075.png">

**Comment by CD4017BE** [comment]
It seems that some neighboring block is providing wrong Forge-Capabilities (returning its inventory although it was asked for Universal Pipe Network capability).

What is that green bowl thing next to the second pipe?
Try if it works with that block removed or if it immediately crashes when an Advanced Universal Pipe is directly placed next to one of these.

**Comment by BenB196** [comment]
Looks like the issue could be related to: https://github.com/thraaawn/BonsaiTrees/issues/37
I will update to the latest version of the mod and retest, thanks.

**Comment by BenB196** [comment]
On a side note, is 1.12.2-1.2.0 an official release? I don't see it listed on Curse for download, though I do see you point other people to the version.

**Comment by CD4017BE** [comment]
I noticed that some bug fixes in that version unfortunately introduced new bugs and I wanted to fix them before putting it as official release on Curse. So consider versions on Github that aren't on Curse yet as beta or still in testing.
