### ISSUE TITLE
Server Log Spam when placing Advanced Universal Pipe

### ISSUE THREAD

**Issue by BenB196** [CD4017BE/InductiveLogistics#22]
### What I did:
If I place an Advance Universal Pipe my server log gets a new line.

Is this a debug tool that was accidentally left in?

### What happened:
Each of these is a for a different pipe.  Tested with most other pipes, and did not get the message

[14:22:56] [Server thread/INFO] [cd4017be_lib]: 1 singleTicks 4 contTicks
[14:22:57] [Server thread/INFO] [cd4017be_lib]: 2 singleTicks 4 contTicks

I was also seeing logs when items were traveling through these pipes, but they looked exactly the same as above.

### What should have happened:
I don't believe I should see this.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.2.1
- CD4017BE_lib-6.2.3
- Forge-14.23.3.2679
- This happens on a server, did not check SSP

**Comment by BenB196** [comment]
The second part of the what happened, about log occurring with item traveling through it appears to be the incorrect assumption.  It looks like it is logging every second when a pipe has either a insert/extract pipe attached to them.

**Comment by CD4017BE** [comment]
Yes this is a [debug function in the library](https://github.com/CD4017BE/CD4017BE_lib/blob/ce55ad5d269c179a9c849f27ff64f23baed2d2f0/src/java/cd4017be/lib/TickRegistry.java#L31) I accidentally left on.
It will probably write a line every time an Advanced Universal Pipe or 32-bit Signal Wire (Automated Redstone) gets a neighbor block update, gets broken/placed or when their chunk unloads/loads.

This will be disabled in the next release.

**Comment by BenB196** [comment]
Thanks, something that is bit of a side note, but I noticed that since the most recent update to ID, items sit around longer in chests before the pipes actually move them.  Is this intended for performance? I saw that a  lot was done to improve it last few patches.

**Comment by CD4017BE** [comment]
The default speed of the Advanced Universal Pipes was only slightly decreased from an operation every 4 ticks (= 5 ops/s) previously to every 5 ticks (= 4 ops/s) now.
However if the inventory that is extracted from contains multiple stacks, they are processed round robin one at a time. So if an item in the inventory can't be inserted at any destination in the pipe network then that operation cycle won't do anything. This can slow things down significantly if inventories contain lots of "invalid" items.

**Comment by BenB196** [comment]
Thanks, this makes sense.

**Comment by CD4017BE** [comment]
[fix](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v6.2.4) already released
