### ISSUE TITLE
Fluid Pipes do not extract fluids from Immersive Petroleum distillation towers

### ISSUE THREAD

**Issue by BenB196** [CD4017BE/InductiveLogistics#23]
### What I did:
_Description of your setup (how devices where configured, connected etc.) and what you did (eventually a screenshot)_
I attached a fluid extraction pipe to an Immersive Engineering distillation tower and a Fluid inject pipe (with a filter, taking off the filter did not fix it) to the tank. With an advanced universal pipe connecting them.

<img width="1127" alt="pipe_setup" src="https://user-images.githubusercontent.com/8277432/39894522-1e310ce6-5475-11e8-9666-7a906af4cdb1.png">

Side note: a standard fluid pipe gets the fluid automatically, but does not actually connect to the tower output for some reason.

### What happened:
_Description of what happened, how things behaved and/or crash report (if any) or log entries (only the relevant parts if any)_
The fluids in the tower did not go anywhere, and the pipes would not move any fluid.

### What should have happened:
_The behavior you expected or would like to have (obsolete for crashes)_
The pipes should extract and transport the fluids to the tank.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.2.1
- CD4017BE_lib-6.2.3
- Forge-14.23.3.2679
- Immersive Engineering Core-0.12-80
- Immersive Engineering-0.12.82
- Immersive Petroleum-1.1.9

**Comment by BenB196** [comment]
I believe I found the issue, but want to confirm that it is working correctly. It looks like only Fluid Destination pipes work now, and fluid inject pipes do not, is this intended?

**Comment by CD4017BE** [comment]
The Advanced Universal Pipes got some new connection types added recently. The previous purpose of injection pipes is now handled by destination pipes. And the injection pipes now work as active retrievers instead, pulling items/fluids from source pipes.
Extraction and injection pipes are the ones that actively supply or drain their connected tank, whereas the destination and source pipes are considered passive, they just mark the targets to get or put things.
In general things can only move between active <-> passive connection but not passive -> passive or active -> active.

About the problem with the normal pipes:
I also recently noticed them disconnecting from Immersive Multiblocks after chunk unloads. I think it may be that sometimes in the first tick after chunk load where the pipe does its logic to connect with neighboring devices, the multiblock structure might not have its inventory/tank capabilities ready to that point, so the pipe assumes it can't connect to it. Giving it a block update should make it recheck and fix it.

**Comment by CD4017BE** [comment]
Maybe I could fix this bug by performing the after load checks via the single tick schedule system in my library since that runs on Forge Game Tick Events that are performed after the main world tick. So this could give the Immersive multiblock structure time do to its initialization stuff first.
