### ISSUE TITLE
Crash when item placer placing work bench

### ISSUE THREAD

**Issue by Snownee** [CD4017BE/InductiveLogistics#25]
### What I did:
Insert more than one workbench into item placer.

### What happened:
Game crashed. [Here](https://paste.ubuntu.com/p/QyYSdGJhvP/) is the crash report.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.2.1
- CD4017BE_lib-6.2.3
- Forge-14.23.3.2698

**Comment by CD4017BE** [comment]
I found out that this happens with all vanilla Blocks that open up a GUI when right-clicked, modded ones as far as I tested worked fine however.
It seems the FakePlayer implementation offered by Forge forgot to stub out some methods.
