### ISSUE TITLE
Overflow Trash Crash Causer

### ISSUE THREAD

**Issue by artdude543** [CD4017BE/InductiveLogistics#28]
Hello! A developer of SevTech Ages, We had this report posted to us in regards to a crash with this mod in an interaction with another mod (IE).

Linked Issue (With details etc..): DarkPacks/SevTech-Ages#2741
See the comment from the IE Dev in regards: https://github.com/DarkPacks/SevTech-Ages/issues/2741#issuecomment-394841375

Any help would be much appreciated! :)

Used Versions:
Minecraft: 1.12.2
InductiveLogistics: 1.2.1
CD4017BE_lib: 6.2.3
Forge: 14.23.3.2679

**Comment by CD4017BE** [comment]
[fix released](https://github.com/CD4017BE/InductiveLogistics/releases/tag/v1.2.3)
