### ISSUE TITLE
Advanced Universal Pipe seem non-functional

### ISSUE THREAD

**Issue by ghost** [CD4017BE/InductiveLogistics#29]
### What I did:
I was initially trying to connect up _Absorption Hopper_ at a mob farm with _Advanced Universal Pipes_ to route both the drops and the xps to storage.  This worked fine with either IL _Fluid Pipes_ or IL _Item Pipes_, so I tried to upgrade to the _Advanced Universal Pipes_.  This did not work at all for me - I even figured out how to "attach" the correct fluid and item Extraction and Injection pipes to the AUP pipes at the Hoppers and configure the hoppers correct.

So I fault reduced the problem to the simplest configuration possible:   Chest => AUP => Chest with item extraction and item injection pipes added to each side of the AUP.  (see screenshot)

![2018-06-26_23 07 04](https://user-images.githubusercontent.com/7958470/41956094-526e590e-7997-11e8-9184-4af1cf010ff5.png)

### What happened:
First thing I noticed is that both the extraction end and the injection end of the Advanced Universal Pipe had red/black [X] graphics on them next to the chest as if they were disabled.  Even if I clicked on the to turn them back on, there was no transfer of items to/from either chest.

### What should have happened:
The pipe ends should come up enabled and the items should transfer.

### Used Versions:
Minecraft 1.12.2
SevTech 3.0.8
InductiveLogistic 1.2.3
CD4017BE_lib 6.2.4
Forge Mod Loader 8.0.99.99
Minecraft Forge 14.23.4.2707

**Comment by CD4017BE** [comment]
To quote an earlier respond to a similar issue:
> The Advanced Universal Pipes got some new connection types added recently. The previous purpose of injection pipes is now handled by destination pipes. And the injection pipes now work as active retrievers instead, pulling items/fluids from source pipes.
Extraction and injection pipes are the ones that actively supply or drain their connected tank, whereas the destination and source pipes are considered passive, they just mark the targets to get or put things.
In general things can only move between active <-> passive connection but not passive -> passive or active -> active.

This is also described in short by the Advanced Universal Pipe's item tooltip.

**Comment by ghost** [comment]
OK, closing bug.  This was not at all obvious.
