### ISSUE TITLE
Crash with Remote Access Pipe and Hoppers

### ISSUE THREAD

**Issue by Nonsanity** [CD4017BE/InductiveLogistics#34]
Placing a remote access pipe between two hoppers, above and below (where the hoppers are aimed doesn't seem to matter), then breaking the top hopper causes a crash.

The cause is, by my guess, to be the lower hopper still trying to access the top one through the RAP, even as it's breaking. Might just need a simple check to make sure the target block still exists instead of trusting the state of the pipe itself to be accurate.

Video: https://youtu.be/-jNfrDn9tQU
Crash Log: https://pastebin.com/gWwgBth1

**Comment by CD4017BE** [comment]
The problem was that I did this check in the method that gives that actual capability but forgot it in the method that just checks whether the capability is available. So the pipe told the bottom hopper "yes I have a capability for you" but then actually returned null when asked for it.
