### ISSUE TITLE
Automated filling from tanks does not seem to be working properly

### ISSUE THREAD

**Issue by md5i** [CD4017BE/InductiveLogistics#38]
### What I did:
Tried to automate filling buckets using a small tank.

Set-up: 

- Place a hopper on the ground, a small tank above that, and another small tank above that.  Place a second hopper leading into the lower small tank.
- Set the lower tank to be in automated filling mode.
- Put an empty bucket into the upper hopper.  It correctly enters the (empty) lower tank.
- Fill the upper tank using a full bucket.

### What happened:

- Water drains into the lower tank.
- Bucket in lower tank does not fill.

### What should have happened:

Bucket in lower tank should have been filled, and lower hopper should have pullout out the filled bucket.

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.3.3
- CD4017BE_lib-6.3.3
- Forge-14.23.5.2768

**Comment by CD4017BE** [comment]
fix released
