### ISSUE TITLE
Tank 8b not showing fluid level with IC2

### ISSUE THREAD

**Issue by madhatr** [CD4017BE/InductiveLogistics#4]
The tank gives no in world indication that it has the fluid it in It when filled with IC2 hot coolant.  You can see the fluid in the gui though.

**Comment by CD4017BE** [comment]
which version are you using?
Because I already released a fix for that in 1.12 but not in 1.11 yet

**Comment by madhatr** [comment]
Sorry yeah I upgraded to 103. Though the tank is doing weird things now.  I had fluid flowing into it with no exit, trying to get it to fill as I seen it was fixed but it never filled up, it was as though it was deleting the fluid.

Though when it was connected back into the loop,  it passed the fluid  along just fine. I'm  going to mess with it get more info and make a new report if need be.

**Comment by madhatr** [comment]
No need to investigate, if I was unclear. When the tank was not filling I was using version 100.  The weirdness I spoke of was the tank doesn't accept fluid from the bottom, which you explained is by design.  

If your investigating fluid flowing through, I was mistaken.   It was just the extra fluid that was contain in the pipes still.   Flow does not exist when injecting from the bottom as designed.

Cheers.
