### ISSUE TITLE
Doesn't launch with cd4017be_lib 6.5.1

### ISSUE THREAD

**Issue by matrix07012** [CD4017BE/InductiveLogistics#43]
### What I did:
I updated cd4017be_lib to the latest version and the game crashes saying it requires [cd4017be_lib@[6.4.10,6.5.0) 

### What happened:
[crash-2020-08-15_18.24.37-server.txt](https://github.com/CD4017BE/InductiveLogistics/files/5079129/crash-2020-08-15_18.24.37-server.txt)

### What should have happened:
Launch

### Used Versions:
- Minecraft-1.12.2
- InductiveLogistics-1.3.4
- CD4017BE_lib-6.5.1
- Forge-14.23.5.2854

**Comment by CD4017BE** [comment]
Sorry I didn't notice the version compatibility range configured in the mod ran out after lib v.6.5.0.
A fixed version is available at CurseForge now.
