### ISSUE TITLE
Unable to sneak click to remove pipe connection from block.

### ISSUE THREAD

**Issue by madhatr** [CD4017BE/InductiveLogistics#5]
Attempting to remove the ejection pipe connection to the block on the right in the following image.  It will not remove.   I can right click and both connections get a red X but that is about it.

v103
1.12.2-forge1.12.2-14.23.1.2554

https://imgur.com/a/TsmJ0

**Comment by CD4017BE** [comment]
sneak?

**Comment by madhatr** [comment]
Yes it was the torches,  thanks.
