### ISSUE TITLE
8B tank not accepting fluid from down/bottom.

### ISSUE THREAD

**Issue by madhatr** [CD4017BE/InductiveLogistics#6]
Placing an injection pipe at the bottom of a Tank results in no fluid entering tank.  The injection pipe shows fluid in it blinking on and off.

When the injection pipe is placed on the side fluid flows in as expected. 

v103
1.12.2-forge1.12.2-14.23.1.2554

**Comment by CD4017BE** [comment]
**Fluid Tank**
...
Automatically outputs contained fluids to the bottom.
...

Fluid Pipes expose their internal buffer tank to external devices to allow convenient interaction with other modded fluid devices, but in this case the tank just emits the fluid it just received back into the pipe.

**Comment by CD4017BE** [comment]
Let me summarize all problems (and solutions) so far:

- [ ]  make pipe direction and filter functionality also effective for access to its internal buffer from other devices
- [ ]  eventually add a button to limit stacksize for fluid container filling to 1 (may be better to automate in some cases)
- [ ] maybe ignore offhand content for sneak-right-click with empty hand
